development:
  secret_key_base: b7bba3b36e474e3b1e9e9db3d8f24f3d4e069ab46e6fd5c42017ae0f544ca55c6b806476ae98dce7914d2458a61260aa13ddcbbceca21a2acb615489ea514ac4
  #email_provider_username: brandonw49@gmail.com
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  #email_provider_password: vmrwrnfxlvhmflgx
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: example.com
  owner_email: <% ENV["OWNER_EMAIL"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  owner_email: <% ENV["ONWER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
